# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/mahsa/mahsa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15src/mahsa/mahsa.proto\"\"\n\x11HelloMahsaRequest\x12\r\n\x05greet\x18\x01 \x01(\t\"&\n\x12HelloMahsaResponse\x12\x10\n\x08nemikham\x18\x01 \x01(\t2P\n\x10GRPCMahsaGreeter\x12<\n\x0fSayHelloToMahsa\x12\x12.HelloMahsaRequest\x1a\x13.HelloMahsaResponse\"\x00\x42\x0bZ\tsrc/mahsab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.mahsa.mahsa_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\tsrc/mahsa'
  _HELLOMAHSAREQUEST._serialized_start=25
  _HELLOMAHSAREQUEST._serialized_end=59
  _HELLOMAHSARESPONSE._serialized_start=61
  _HELLOMAHSARESPONSE._serialized_end=99
  _GRPCMAHSAGREETER._serialized_start=101
  _GRPCMAHSAGREETER._serialized_end=181
# @@protoc_insertion_point(module_scope)
